
DROP DATABASE IF EXISTS test138;
CREATE DATABASE test138;
use test138;

CREATE TABLE EMPLOYEE (
    FNAME varchar(255) NOT NULL,
    MINIT character,
    LNAME varchar(255),
    SSN varchar(20) NOT NULL,
    BDATE DATE NOT NULL,
    ADDRESS varchar(255),
    SEX ENUM('M','F'),
    SALARY DECIMAL (12,4),
    SUPERSSN varchar(20),
    DNO int references DEPARTMENT(DNUMBER),
    PRIMARY KEY (SSN),
    FOREIGN KEY (SUPERSSN) references EMPLOYEE(SSN)
);


CREATE TABLE DEPARTMENT (
    DNAME varchar(255) NOT NULL,
    DNUMBER int NOT NULL,
    MGRSSN varchar(20),
    MGRSTARTDATE DATE,
    PRIMARY KEY (DNUMBER),
    FOREIGN KEY (MGRSSN) references EMPLOYEE(SSN)
);

CREATE TABLE DEPT_LOCATIONS (
    DNUMBER int NOT NULL,
    DLOCATION varchar(255) NOT NULL,
    PRIMARY KEY (DNUMBER,DLOCATION),
    FOREIGN KEY (DNUMBER) references DEPARTMENT(DNUMBER)
);

CREATE TABLE PROJECT (
    PNAME varchar(255) NOT NULL,
    PNUMBER int NOT NULL,
    PLOCATION varchar(255),
    DNUMBER int ,
    PRIMARY KEY (PNUMBER),
    FOREIGN KEY (DNUMBER) references DEPARTMENT(DNUMBER)

);

CREATE TABLE WORKS_ON (
    ESSN varchar(20) references EMPLOYEE(SSN),
    PNUMBER int NOT NULL references PROJECT(PNUMBER),
    PLOCATION varchar(255),
    DNUMBER int,
    PRIMARY KEY (ESSN,PNUMBER),
    FOREIGN KEY (DNUMBER) references DEPARTMENT(DNUMBER),
    FOREIGN KEY (PNUMBER) references PROJECT(PNUMBER)

);


CREATE TABLE DEPENDANT (
    DEPENDANTNAME varchar(255) NOT NULL,
    ESSN varchar(20) references EMPLOYEE(SSN),
    BDATE DATE NOT NULL,
    SEX ENUM('M','F'),
    RELATIONSHIP varchar(50),
    PRIMARY KEY (ESSN,DEPENDANTNAME),
    FOREIGN KEY (ESSN) references EMPLOYEE(SSN)
);

INSERT INTO EMPLOYEE VALUES 
("John","B","Smith","123456789","1965-01-09","731 Fondren, Houston, TX"),

